CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id     int generated by default as identity primary key,
    mpa_name   varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id      int generated by default as identity primary key,
    genre_name    varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      bigint generated by default as identity primary key,
    film_name    varchar(100) NOT NULL,
    description  varchar(200) NOT NULL,
    release_date date         NOT NULL,
    duration     int          NOT NULL,
    mpa_id    int          NOT NULL REFERENCES mpa (mpa_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id   bigint REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id  int REFERENCES genres (genre_id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  bigint generated by default as identity primary key,
    user_email    varchar(100) NOT NULL,
    user_login    varchar(100) NOT NULL,
    user_name     varchar(100),
    birthday      date
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id  bigint REFERENCES films (film_id) ON DELETE CASCADE,
    user_id  bigint  REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id    bigint   REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id  bigint REFERENCES users (user_id) ON DELETE CASCADE,
    status     boolean
);